const cols = [
    { id: 'name', label: 'Name', minWidth: 155 },
    { id: 'day1', label: '1', minWidth: 25, align: 'center', },
    { id: 'day2', label: '2', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day3', label: '3', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day4', label: '4', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day5', label: '5', minWidth: 25, align: 'center', },
    { id: 'day6', label: '6', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day7', label: '7', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day8', label: '8', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day9', label: '9', minWidth: 25, align: 'center', },
    { id: 'day10', label: '10', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day11', label: '11', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day12', label: '12', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day13', label: '13', minWidth: 25, align: 'center', },
    { id: 'day14', label: '14', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day15', label: '15', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day16', label: '16', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day17', label: '17', minWidth: 25, align: 'center', },
    { id: 'day18', label: '18', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day19', label: '19', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day20', label: '20', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day21', label: '21', minWidth: 25, align: 'center', },
    { id: 'day22', label: '22', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day23', label: '23', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day24', label: '24', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day25', label: '25', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day26', label: '26', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day27', label: '27', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day28', label: '28', minWidth: 25, align: 'center', },
    { id: 'day29', label: '29', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day30', label: '30', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
    { id: 'day31', label: '31', minWidth: 25, align: 'center', format: (value) => value.toLocaleString('en-US'), },
]
export default cols;