import photo from '../../image/student.png';
const TeachersRow = [
    { id: 1,roll: '171966', photo: photo, name: 'Ariful Islam', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 2,roll: '171967', photo: photo, name: 'Shoriful Islam', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 3,roll: '171968', photo: photo, name: 'Jahed Kamal', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 4,roll: '171969', photo: photo, name: 'Yubraj Sing', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 5,roll: '171970', photo: photo, name: 'Sunny Mohammad', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 6,roll: '171971', photo: photo, name: 'Abdul Khalek', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 7,roll: '171972', photo: photo, name: 'Selim Khan', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 8,roll: '171973', photo: photo, name: 'Saidul Islam', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 9,roll: '171974', photo: photo, name: 'Mutafa Kamal', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 10,roll: '171975', photo: photo, name: 'Munni Akter', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 11,roll: '171976', photo: photo, name: 'Shatu Das', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 12,roll: '171977', photo: photo, name: 'Samir Khan', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 13,roll: '171978', photo: photo, name: 'Sahed Islam', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },
    { id: 14,roll: '171979', photo: photo, name: 'Karim Khan', gender: 'male', department: 'Computer', section: 'parent', address: 'khagori',  father: 'Shirajul Islam',mother: 'Shamim Akter',religion: 'Islam', fatherOccuption: 'business' ,admissionDate: '01-08-2018', email: 'ariful.og@gmail.com', dob: '25-08-1997', phone: '01830134593' },

];
export default TeachersRow;